baseURL = 'https://www.simonw.eu'
locale = 'en-gb'
enableGitInfo = true
enableRobotsTXT = true
[Params.author]
name = 'Simon Wögerbauer'
website = 'https://www.simonw.eu'
email = 'simonwoegerbauer#outlook.com'
github = 'simonwoegerb'
discord = 'austerr'
linkedin = "https://www.linkedin.com/in/simon-w%C3%B6gerbauer-4b7a39347/"
orcid = '0009-0005-9731-2522'
[Params]
sourceRepo = "https://github.com/simonwoegerb/www.simonw.eu/tree/main/content/"
showSource = true
dateFormat = ":date_long"
commit = "https://github.com/simonwoegerb/www.simonw.eu/commit/"
homeTitle = '''Formula Student Devlogs'''
subTitle = "Engineering Development in Formula Student and Embedded Systems"
since = 2026
rss = true
readingTime = true
wordCount = true
mainSections = ["posts", "pages"]
toc = false
color = "light"
logo = "/img/me.jpg"
mathEngine = "mathjax"
disclaimerText = "No guarantees for any content of this page. All images used under Fair Use (non-commercially). This project is not in any way affiliated with Formula Student in any official capacity."
[[Params.bigimg]]
src = "img/WAM01_Render.png"
desc = "© Copyright: FHOOE Racing Team"
[[Params.bigimg]]
src = "img/TU_Braunschweig_Car.jpg"
desc = "© Copyright: TU Braunschweig"
[[module.imports]]
path = "github.com/halogenica/beautifulhugo"
[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About Me"
url = "/about/"
weight = 3
[sitemap]
changefreq = 'weekly'
disable = false
priority = 0.8
