baseURL = 'https://www.simonw.eu'
locale = 'en-us'
title = '''Simon's Blog'''
enableGitInfo = true
[Params.author]
name = 'Simon Woegerbauer'
website = 'https://www.simonw.eu'
email = 'simonwoegerbauer#outlook.com'
github = 'simonwoegerb'
[Params]
sourceRepo = "https://github.com/simonwoegerb/www.simonw.eu"
dateFormat = ":date_long"
commit = false
since = 2026
rss = true
readingTime = true
wordCount = true
mainSections = ["post", "posts", "page"]
logo = "/img/me.jpg"
[[module.imports]]
path = "github.com/halogenica/beautifulhugo"
